controller_list:
  - name: fake_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - plat_joint
      - manip_joint
  - name: fake_gripper_controller
    type: $(arg fake_execution_type)
    joints:
      - garra1_joint
      - garra2_joint
initial:  # Define initial robot poses per group
  - group: arm
    pose: initial_pose
  - group: gripper
    pose: close