arm:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005
  goal_joint_tolerance: 0.01
  goal_position_tolerance: 0.01
  goal_orientation_tolerance: 0.01
  position_tolerance: 0.01     # Tolerância de posição em metros (1 cm)
  orientation_tolerance: 0.01  # Tolerância de orientação em radianos
  joint_tolerance: 0.01        # Tolerância de juntas em radianos