arm_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - plat_joint
    - manip_joint
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0
    plat_joint: {trajectory: 0.1, goal: 0.1}
    manip_joint: {trajectory: 0.1, goal: 0.1}
  gains:
    plat_joint:
      p: 10000
      d: 1
      i: 1
      i_clamp: 1
    manip_joint:
      p: 10000
      d: 1
      i: 1
      i_clamp: 1
gripper_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - garra1_joint
    - garra2_joint
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0
    garra1_joint: {trajectory: 0.1, goal: 0.1}
    garra2_joint: {trajectory: 0.1, goal: 0.1}
  gains:
    garra1_joint:
      p: 4000
      d: 1
      i: 1
      i_clamp: 1
    garra2_joint:
      p: 4000
      d: 1
      i: 1
      i_clamp: 1