poses:
  pose_inicial:
    plat_angle: 0.0
    plat_duration: 2.0
    manip_angle: 90.0
    manip_duration: 2.0
  pose_baixo:
    plat_angle: 0.0
    plat_duration: 2.0
    manip_angle: 0.0
    manip_duration: 2.0
  pose_pegar_bloco_5:
    plat_angle: 0.0
    plat_duration: 2.0
    manip_angle: 30.0
    manip_duration: 2.0
  pose_pegar_bloco_10:
    plat_angle: 0.0
    plat_duration: 2.0
    manip_angle: 20.0
    manip_duration: 2.0
  pose_pegar_bloco_15:
    plat_angle: 0.0
    plat_duration: 2.0
    manip_angle: 10.0
    manip_duration: 2.0
  pose_deposito_1:
    plat_angle: 160.0
    plat_duration: 2.0
    manip_angle: 50.0
    manip_duration: 2.0
  pose_deposito_2:
    plat_angle: 180.0
    plat_duration: 2.0
    manip_angle: 50.0
    manip_duration: 2.0
  pose_deposito_3:
    plat_angle: 200.0
    plat_duration: 2.0
    manip_angle: 50.0
    manip_duration: 2.0
